### ISSUE TITLE
Fn Key Repeater

### ISSUE THREAD

**Issue by tsioukas** [navhaxs/BrightnessTray#1]
This is not exactly issue, it's a little request for new feature.

This app works great on many laptops, but a lot of laptops with new Windows doesn't release updated drivers for function keys. But the fastest way to change brightness is this.

Is it possible to create a mechanism that listen functions keys (for most laptops Fn+F5, Fn+F6) to recreate this feature. You can also to create a form to choose manually functions keys that set brightness up and down.

Thanks

P.S. Good job anyway

**Comment by navhaxs** [comment]
About using the function keys, I did try autohotkey to test if it was possible to detect the special fn keys (http://www.autohotkey.com/docs/commands/KeyHistory.htm), but it was not very promising. I also tried this C# sample (http://blogs.msdn.com/b/toub/archive/2006/05/03/589423.aspx).

It looks like it would be, at best, very difficult to hook into the fn keys - and very much dependent on the notebook brand/model. If you have a thinkpad and the hotkey drivers installed (I don't), you could try something like this: https://forums.lenovo.com/t5/Windows-7-Discussion/Fn-Fx-key-mapping-Windows-7/td-p/429553

Or Win+X mobility center?

Thanks for the feedback!
