### ISSUE TITLE
Hotkeys [Request]

### ISSUE THREAD

**Issue by 32-bit-link** [navhaxs/BrightnessTray#11]
so a lot of laptops do not have the proper drivers to use the brightness keys because the manufacturers don't support it anymore. So I think that adding customizable hotkeys is some way would be awesome!

**Comment by navhaxs** [comment]
Hey @32-bit-link 
Whilst this feature would be possible from a technical perspective, writing your own AutoHotKey script would be a better solution for this - after all this sort of thing is the very reason that AutoHotKey exists (no need to reinvent the wheel) ;)

Something like this... https://www.autohotkey.com/boards/viewtopic.php?t=26921&p=126135

**Comment by 32-bit-link** [comment]
> Hey @32-bit-link
> Whilst this feature would be possible from a technical perspective, writing your own AutoHotKey script would be a better solution for this - after all this sort of thing is the very reason that AutoHotKey exists (no need to reinvent the wheel) ;)
> 
> Something like this... https://www.autohotkey.com/boards/viewtopic.php?t=26921&p=126135

ok thanks, I will try that!
