### ISSUE TITLE
Feautre request: brightness level in tray icon and slider

### ISSUE THREAD

**Issue by zoidy** [navhaxs/BrightnessTray#3]
Hi this is exactly what I was looking for. Simple, clean and touch friendly. 

Would it be possible to have an option to show the brightness level in the tray icon and in the slider panel? This would be incredibly useful so as to a) see the current brightness at a glance b) see what percent you are changing to.

**Comment by navhaxs** [comment]
Mmm yes I think that can be achieved.

e.g. Showing a 75% text label between the "sun icon" and slider (easy), and for the system tray, a white 75% text rather than the icon.

I'll have some time in the coming weeks to investigate.

**Comment by navhaxs** [comment]
Feature added.

https://github.com/navhaxs/BrightnessTray/releases/tag/v1.1
